# 03 · Demonstração e Avaliação

**Tech Challenge – Fase 4 · Voice of Customer Intelligence com RAG** · RM371084

1. Perguntas de negócio do enunciado, com respostas e evidências citadas;
2. Tratamento de perguntas **sem evidências suficientes** e **fora do escopo**;
3. Avaliação quantitativa da recuperação e da fundamentação das respostas.

In [1]:
import sys, time
sys.path.insert(0, "../src")
import pandas as pd
from vocrag import config
from vocrag.rag import VoCRAG
from vocrag.display import show

rag = VoCRAG()
respostas = {}
def perguntar(q, **kw):
    r = rag.ask(q, **kw); respostas[q] = r; show(r); return r

## 1. Exploração da voz do cliente

### Investigação de reclamações

In [2]:
perguntar("Quais são os principais problemas relatados pelos clientes em suas avaliações?");

### ❓ Quais são os principais problemas relatados pelos clientes em suas avaliações?

**Status:** ✅ Respondida com evidências

**Consultas usadas na busca:** `Quais são os principais problemas relatados pelos clientes em suas avaliações?` · `o produto veio quebrado e fiquei muito frustrado` · `a entrega atrasou e o atendimento foi péssimo` · `o produto não funciona e a qualidade é muito ruim` · `veio faltando peças e o vendedor não responde`

**Perfil do tema:** ≥2317 avaliações relacionadas · nota média 1.74 · 77.3% com nota 1-2

**Modelo de geração:** `gemini-3.5-flash-lite`

---

Com base na amostra de avaliações recuperadas, que conta com pelo menos 2317 avaliações semanticamente relacionadas (nota média de 1.74 e 77.3% de notas 1 ou 2), os principais problemas relatados pelos clientes são:

- **Problemas de qualidade e funcionamento do produto**: Os clientes relatam que os produtos apresentam funcionamento inadequado [R1, R12], baixa qualidade ou fragilidade [R5, R13], além de itens que chegam quebrados [R3, R7], avariados [R6], faltando peças [R5] ou mesmo falsificados [R3]. Também há relatos de itens entregues em desacordo com o anúncio [R10].

- **Atrasos e falhas na entrega**: Há registros de demora excessiva nos prazos e atrasos na entrega dos pedidos [R2, R8, R11, R15], além de casos de pedidos não entregues ou com grande atraso sem dar satisfação ao cliente [R4, R9, R14]. A amostragem indica que 20.8% dos pedidos entregues o foram após o prazo.

- **Atendimento e suporte insatisfatórios**: Clientes criticam o péssimo atendimento prestado [R4, R8, R9], falta de retorno ou demora para responder e descaso com o consumidor [R8, R14], além de dificuldades ou demora na realização de estornos [R9] e cobrança indevida de postagem [R10].


> **Limitações:** A resposta baseia-se em uma amostra recuperada de 15 avaliações detalhadas e em estimativas agregadas de um universo de pelo menos 2317 avaliações. Como a amostra é qualitativa e restrita, pode haver viés de negatividade, visto que a nota média geral do tema é baixa (1.74) e 77.3% das avaliações possuem notas 1 ou 2.

**Evidências citadas (15):**

### Investigação de um tema específico

In [3]:
perguntar("O que os clientes relatam sobre problemas relacionados à entrega?");

### ❓ O que os clientes relatam sobre problemas relacionados à entrega?

**Status:** ✅ Respondida com evidências

**Consultas usadas na busca:** `O que os clientes relatam sobre problemas relacionados à entrega?` · `o produto atrasou muito e não chegou no prazo` · `a transportadora demorou demais para entregar meu pedido` · `tive problemas com a entrega e o rastreio não atualizava`

**Perfil do tema:** ≥1433 avaliações relacionadas · nota média 2.97 · 45.1% com nota 1-2

**Modelo de geração:** `gemini-3.5-flash-lite`

---

Com base na amostra recuperada, os clientes relatam os seguintes problemas relacionados à entrega:

* **Atrasos na entrega**: Os clientes apontam que os produtos não chegam dentro do prazo estabelecido, ocorrendo atrasos que variam de 2 a 21 dias após o vencimento do prazo [R1, R2, R4, R5, R8, R10, R11]. Há relatos de que o produto não foi recebido mesmo após o término do prazo [R1, R7], além de frustração com prazos longos de espera, como um caso com prazo inicial de 1 mês [R9]. O perfil geral indica que 26.2% dos pedidos entregues o foram após o prazo [Perfil].

* **Falta de atendimento e suporte**: Um cliente relatou ter enviado e-mail questionando sobre a entrega atrasada e não ter obtido retorno da loja [R9].

* **Incompletude do pedido**: Em um caso, o cliente relatou que fez dois pedidos com o mesmo rastreamento, mas recebeu apenas um deles [R13].


> **Limitações:** A análise é baseada em uma amostra de 15 avaliações recuperadas e em estimativas de um universo de pelo menos 1433 avaliações semanticamente relacionadas (nota média de 2.97 e 45.1% com nota 1 ou 2). A amostra foca predominantemente em menções a prazos de entrega e pode não abranger exaustivamente outros problemas logísticos complexos.

**Evidências citadas (10):**

### Busca por experiências positivas

In [4]:
perguntar("Quais aspectos da experiência de compra são mais elogiados pelos clientes?");

### ❓ Quais aspectos da experiência de compra são mais elogiados pelos clientes?

**Status:** ✅ Respondida com evidências

**Filtro de metadados aplicado:** `{'review_score': {'$gte': 4}}`

**Consultas usadas na busca:** `Quais aspectos da experiência de compra são mais elogiados pelos clientes?` · `o atendimento foi excelente e chegou super rápido` · `fiquei muito satisfeito com a qualidade do produto e a compra` · `entrega antes do prazo e vendedor muito atencioso` · `adorei a compra, superou todas as minhas expectativas`

**Perfil do tema:** ≥3331 avaliações relacionadas · nota média 4.86 · 0.0% com nota 1-2

**Modelo de geração:** `gemini-3.5-flash-lite`

---

Com base na amostra recuperada, os clientes destacam os seguintes aspectos positivos da experiência de compra:

- **Rapidez e cumprimento do prazo de entrega**: Os clientes elogiam a entrega super rápida, o recebimento antes do prazo previsto e o envio bem feito [R1, R3, R5, R7, R8, R9, R11, R13, R14]. Apenas uma avaliação menciona atraso de dois dias, mas ainda assim expressa satisfação geral [R6].
- **Qualidade dos produtos**: Há elogios frequentes de que os produtos são ótimos, de excelente qualidade e que superaram as expectativas dos compradores [R1, R2, R7, R12, R14].
- **Atendimento excelente e atencioso**: O atendimento prestado pelos vendedores e fornecedores é apontado como excelente e muito atencioso [R4, R5, R8, R10, R13].


> **Limitações:** A análise baseia-se em um recorte de 15 avaliações recuperadas de um total estimado em pelo menos 3.331 avaliações com nota maior ou igual a 4. As conclusões refletem apenas as opiniões contidas nessa amostra específica.

**Evidências citadas (14):**

### Investigação de insatisfação

In [5]:
perguntar("Quais padrões podem ser identificados nas avaliações de clientes insatisfeitos?");

### ❓ Quais padrões podem ser identificados nas avaliações de clientes insatisfeitos?

**Status:** ✅ Respondida com evidências

**Filtro de metadados aplicado:** `{'review_score': {'$lte': 2}}`

**Consultas usadas na busca:** `Quais padrões podem ser identificados nas avaliações de clientes insatisfeitos?` · `fiquei muito decepcionado com a compra` · `o produto veio com defeito e não funciona` · `péssimo atendimento e não recomendo` · `odiei a experiência de compra`

**Perfil do tema:** ≥2212 avaliações relacionadas · nota média 1.15 · 100.0% com nota 1-2

**Modelo de geração:** `gemini-3.5-flash-lite`

---

Com base na amostra recuperada de avaliações com notas baixas (nota média de 1.15, abrangendo 2212 avaliações no total), é possível identificar os seguintes padrões e temas de insatisfação: **Problemas com o funcionamento e qualidade do produto**: Clientes relatam com frequência que os produtos chegam com defeito, não funcionam, não ligam ou apresentam má qualidade, o que engloba falhas em relógios, eletrônicos com touchscreen inoperante, itens que não funcionam e produtos sem qualidade [R3, R5, R6, R7, R9, R10, R14]. **Atrasos e falhas na entrega**: O perfil geral indica que 28.3% dos pedidos foram entregues após o prazo, com relatos específicos de demora excessiva, descumprimento de prazos, falta de profissionalismo e entregas atrasadas [R1, R2, R4, R13]. **Problemas na embalagem, sujeira e estado do item**: Há registros de produtos entregues soltos em caixas sujas exigindo limpeza, itens com embalagem suja e mal acabada, e produtos com lacre rompido em embalagem não original que parecem usados [R4, R12, R15]. **Atendimento ruim e dificuldade no pós-venda**: Os clientes reportam péssimo atendimento e dificuldade no processo de troca, incluindo falhas no sistema e emails que não são enviados [R1, R8, R11].


> **Limitações:** A análise é baseada em uma amostra recuperada de 15 avaliações detalhadas extraídas de um universo estimado de 2212 avaliações com nota menor ou igual a 2. A frequência dos problemas na amostra geral é uma estimativa e pode não refletir a proporção exata de todas as categorias do catálogo.

**Evidências citadas (15):**

### Exploração baseada em evidências

In [6]:
perguntar("Quais avaliações sustentam a conclusão de que existem problemas recorrentes relacionados ao prazo de entrega?");

### ❓ Quais avaliações sustentam a conclusão de que existem problemas recorrentes relacionados ao prazo de entrega?

**Status:** ✅ Respondida com evidências

**Consultas usadas na busca:** `Quais avaliações sustentam a conclusão de que existem problemas recorrentes relacionados ao prazo de entrega?` · `o produto atrasou muito e chegou depois do prazo` · `a entrega demorou semanas além da data prevista` · `meu pedido não chegou no prazo combinado` · `tive problemas com o atraso na entrega da compra`

**Perfil do tema:** ≥1567 avaliações relacionadas · nota média 3.14 · 40.4% com nota 1-2

**Modelo de geração:** `gemini-3.5-flash-lite`

---

Com base na amostra recuperada, existem vários relatos que sustentam a existência de problemas relacionados a prazos de entrega e atrasos, estimados a partir de uma amostra de pelo menos 1567 avaliações relacionadas, onde 40,4% possuem nota 1 ou 2 e 23,3% dos pedidos entregues sofreram atraso:

* **Atrasos na entrega e descumprimento de prazos**: Diversos clientes relatam que os produtos não foram entregues dentro do prazo estipulado [R3, R8, R10, R11], incluindo casos de pedidos cancelados por falta de entrega no prazo [R4, R5], demora na separação do produto que estoura o prazo estimado [R9], e reclamações sobre prazos longos ou demora na entrega mesmo quando entregues no prazo [R2, R15].

* **Cumprimento ou antecipação do prazo**: Por outro lado, há avaliações de clientes que receberam os produtos no prazo combinado ou até mesmo antes do prazo [R1, R6, R7, R13, R14].


> **Limitações:** A análise é baseada em uma amostra recuperada de 15 avaliações detalhadas e métricas estimadas de um universo de pelo menos 1567 avaliações. As menções refletem experiências subjetivas dos clientes nas categorias informadas.

**Evidências citadas (14):**

### Qualidade dos produtos

In [7]:
perguntar("Existem padrões recorrentes nas avaliações relacionadas à qualidade dos produtos?");

### ❓ Existem padrões recorrentes nas avaliações relacionadas à qualidade dos produtos?

**Status:** ✅ Respondida com evidências

**Consultas usadas na busca:** `Existem padrões recorrentes nas avaliações relacionadas à qualidade dos produtos?` · `o produto veio com defeito e quebrou muito rápido` · `a qualidade é péssima, o material parece muito frágil` · `produto excelente, superou minhas expectativas em relação ao acabamento`

**Perfil do tema:** ≥2342 avaliações relacionadas · nota média 3.42 · 34.5% com nota 1-2

**Modelo de geração:** `gemini-3.5-flash-lite`

---

Com base na amostra recuperada, foram identificados os seguintes padrões recorrentes relacionados à qualidade dos produtos:

- **Superação de expectativas e bom acabamento**: Vários clientes destacam que os produtos superaram suas expectativas [R1, R5, R9, R11, R14], apresentam ótimo acabamento [R1], excelente material [R11, R14] e bom custo-benefício [R8]. Este ponto é sustentado por 7 avaliações.

- **Baixa qualidade e fragilidade**: Há relatos de insatisfação devido a produtos mal acabados, frágeis ou com qualidade muito ruim, sendo comparados desfavoravelmente a produtos de menor valor [R2, R6]. Além disso, há menções de itens que chegaram quebrados ou com defeito de fabricação [R3, R12]. Este ponto é sustentado por 4 avaliações.


> **Limitações:** A análise baseia-se em uma amostra recuperada de 15 avaliações detalhadas, inseridas em um universo estimado de pelo menos 2342 avaliações (com nota média de 3.42 e 34.5% de notas 1 ou 2). A amostra contém tanto avaliações altamente positivas quanto negativas, permitindo observar polarização, mas não substitui uma leitura exaustiva de todo o volume de dados.

**Evidências citadas (10):**

### Atendimento e vendedores

In [8]:
perguntar("Como os clientes descrevem o atendimento e a comunicação com os vendedores?");

### ❓ Como os clientes descrevem o atendimento e a comunicação com os vendedores?

**Status:** ✅ Respondida com evidências

**Consultas usadas na busca:** `Como os clientes descrevem o atendimento e a comunicação com os vendedores?` · `o vendedor não respondeu minhas mensagens` · `fui muito bem atendido pelo vendedor que tirou todas as dúvidas` · `a comunicação com o vendedor foi péssima e demorada` · `tive um ótimo suporte do vendedor após a compra`

**Perfil do tema:** 658 avaliações relacionadas · nota média 4.04 · 20.2% com nota 1-2

**Modelo de geração:** `gemini-3.5-flash-lite`

---

Os clientes descrevem o atendimento e a comunicação com os vendedores de maneiras distintas, abrangendo experiências tanto positivas quanto negativas:

- **Dificuldades e falhas na comunicação**: Há relatos de que é difícil manter um diálogo com o vendedor [R1], ocorrendo demora no retorno após a compra [R5] e pós-venda que deixa a desejar com comunicação difícil [R10]. Um cliente relatou falta de profissionalismo e falta de comunicação quando o produto foi enviado para os correios com prazo alterado [R4]. Outro cliente mencionou falta de atenção do vendedor por enviar itens em desacordo com o anúncio [R14].

- **Atendimento excelente einformativo**: Em contrapartida, clientes descrevem vendedores como excelentes [R3], atenciosos [R15] e que prestam um bom atendimento [R8]. Há elogios para vendedores que fornecem todas as informações necessárias [R12], que cumprem o que dizem sobre o produto [R6] e que garantem entregas corretas e no prazo [R7, R11].


> **Limitações:** A análise é baseada em uma amostra de 15 avaliações recuperadas, refletindo apenas as opiniões contidas nesse grupo específico, enquanto o perfil geral indica uma base de 658 avaliações com nota média de 4.04 e 20.2% de notas 1 ou 2.

**Evidências citadas (12):**

## 2. Perguntas sem evidências suficientes ou fora do escopo

O sistema deve **reconhecer seus limites**. Testamos os três cenários do enunciado:

* **fora do escopo** — o tema não tem relação com avaliações de clientes;
* **sem avaliações relevantes** — tema do domínio de e-commerce, mas que não aparece na base;
* **evidências insuficientes** — a busca encontra textos parecidos, mas que não respondem à pergunta.

In [9]:
perguntar("Qual é a capital da Austrália?");

### ❓ Qual é a capital da Austrália?

**Status:** 🚫 Fora do escopo da base

---

Esta pergunta está fora do escopo da base de conhecimento, que contém apenas avaliações de clientes do e-commerce. Motivo: A pergunta trata de geografia e informações políticas, não tendo relação com compras ou experiência de clientes.

In [10]:
perguntar("Qual foi o faturamento da Olist em 2018 e qual a margem de lucro da empresa?");

### ❓ Qual foi o faturamento da Olist em 2018 e qual a margem de lucro da empresa?

**Status:** 🚫 Fora do escopo da base

---

Esta pergunta está fora do escopo da base de conhecimento, que contém apenas avaliações de clientes do e-commerce. Motivo: A pergunta solicita métricas financeiras de faturamento e margem de lucro, dados internos que não constam em avaliações de clientes.

In [11]:
perguntar("O que os clientes acham do pagamento com criptomoedas na loja?");

### ❓ O que os clientes acham do pagamento com criptomoedas na loja?

**Status:** ⚠️ Evidências insuficientes (avaliação do modelo)

**Consultas usadas na busca:** `O que os clientes acham do pagamento com criptomoedas na loja?` · `paguei com criptomoeda e deu tudo certo na compra` · `tive problemas para usar bitcoin como forma de pagamento` · `poderia ter mais opções de pagamento com criptomoedas`

**Perfil do tema:** 46 avaliações relacionadas · nota média 4.43 · 8.7% com nota 1-2

**Modelo de geração:** `gemini-3.5-flash-lite`

---

As avaliações recuperadas e o perfil das avaliações não contêm nenhuma menção ou informação sobre o uso ou a opinião de clientes em relação ao pagamento com criptomoedas na loja.


> **Limitações:** A amostra recuperada não aborda o tema de criptomoedas, focando apenas em prazos de entrega, qualidade dos produtos recebidos e experiências gerais de compra.

**Evidências recuperadas (15):**

In [12]:
perguntar("O que os clientes falam sobre a experiência de compra pelo assistente de voz Alexa?");

### ❓ O que os clientes falam sobre a experiência de compra pelo assistente de voz Alexa?

**Status:** ⚠️ Evidências insuficientes (avaliação do modelo)

**Consultas usadas na busca:** `O que os clientes falam sobre a experiência de compra pelo assistente de voz Alexa?` · `comprei usando a alexa e foi super prático` · `tive problemas para fazer o pedido pela alexa` · `a experiência de compra por comando de voz da alexa funcionou bem`

**Perfil do tema:** 395 avaliações relacionadas · nota média 4.73 · 3.3% com nota 1-2

**Modelo de geração:** `gemini-3.1-flash-lite`

---

Não foi possível responder à pergunta do gestor, pois as avaliações fornecidas não mencionam a experiência de compra através do assistente de voz Alexa. Os relatos concentram-se em temas como qualidade do produto [R3, R5, R13, R14], agilidade na entrega [R5, R6, R13, R15] e problemas pontuais como itens faltantes [R2], produtos com aspecto de usados [R9] ou dificuldades em processos de cancelamento [R12].


> **Limitações:** A amostra de 15 avaliações analisadas não contém qualquer menção a assistentes de voz ou à plataforma Alexa, impossibilitando a extração de insights sobre esse canal específico.

**Evidências citadas (9):**

**Recorte sem avaliações relevantes.** Aqui a busca roda dentro de um recorte extraído da pergunta (clientes do
Acre + informática, apenas 5 avaliações no total) e nenhuma passa do limiar de relevância: a **guarda de evidência
mínima** encerra o fluxo **sem chamar o LLM de geração**.

In [2]:
perguntar("Clientes do Acre relatam que produtos de informática chegam quebrados?");

### ❓ Clientes do Acre relatam que produtos de informática chegam quebrados?

**Status:** ⚠️ Sem evidências suficientes na recuperação

**Filtro de metadados aplicado:** `{'$and': [{'product_category': {'$in': ['informatica_acessorios']}}, {'customer_state': {'$in': ['AC']}}]}`

**Consultas usadas na busca:** `Clientes do Acre relatam que produtos de informática chegam quebrados?` · `o produto de informatica chegou quebrado` · `veio danificado o item de informatica` · `quebrou na entrega o computador e acessorios`

---

Não encontrei avaliações suficientemente relacionadas a esta pergunta para sustentar uma resposta (0 avaliação(ões) acima do limiar de relevância; mínimo 5). Prefiro não responder a gerar uma conclusão sem evidências.

## 3. Avaliação

Não existe um gabarito rotulado de “avaliações relevantes” para cada pergunta, então usamos **métricas proxy**
baseadas nos metadados, que **não** são usados na recuperação (a busca é puramente semântica sobre o texto):

* **Coerência de sentimento**: para perguntas sobre problemas, a % das evidências com nota 1–2 deveria ser alta;
  para perguntas sobre elogios, a % com nota 4–5.
* **Coerência temática (entrega)**: para perguntas sobre entrega, a % de evidências de pedidos atrasados ou não
  entregues deveria ser muito maior que a taxa da base.
* **Fundamentação**: % das evidências citadas na resposta e quantidade de citações inválidas.

Também comparamos o pipeline **com e sem a transformação da pergunta** (multi-query).

In [13]:
docs = pd.read_parquet(config.DOCS_PATH)
base_neg = (docs.review_score <= 2).mean(); base_pos = (docs.review_score >= 4).mean()
base_entrega = (docs.delivered_late.eq(True) | (docs.order_status != "delivered")).mean()
print(f"Taxas na base: nota 1-2 = {base_neg:.0%} | nota 4-5 = {base_pos:.0%} | atrasado ou não entregue = {base_entrega:.0%}")

AVAL = {
    "Quais são os principais problemas relatados pelos clientes em suas avaliações?": "neg",
    "Quais padrões podem ser identificados nas avaliações de clientes insatisfeitos?": "neg",
    "Existem padrões recorrentes nas avaliações relacionadas à qualidade dos produtos?": None,
    "Quais aspectos da experiência de compra são mais elogiados pelos clientes?": "pos",
    "O que os clientes mais elogiam sobre a entrega?": "pos",
    "O que os clientes relatam sobre problemas relacionados à entrega?": "entrega",
    "Quais avaliações sustentam a conclusão de que existem problemas recorrentes relacionados ao prazo de entrega?": "entrega",
    "Quais reclamações relacionadas à entrega aparecem com maior frequência?": "entrega",
}

def metricas(evs, alvo):
    m = pd.DataFrame([e.metadata for e in evs])
    if m.empty: return {}
    atraso = m.get("delivered_late", pd.Series(dtype=object)).eq(True) | (m["order_status"] != "delivered")
    return {"evidencias": len(m), "sim_media": round(sum(e.similarity for e in evs) / len(evs), 3),
            "%nota_1_2": round((m.review_score <= 2).mean() * 100), "%nota_4_5": round((m.review_score >= 4).mean() * 100),
            "%atraso_ou_nao_entregue": round(atraso.mean() * 100)}

linhas = []
rag_sem = VoCRAG(use_query_rewriting=False)
for q, alvo in AVAL.items():
    for nome, sistema in [("com multi-query", rag), ("sem multi-query", rag_sem)]:
        r = respostas[q] if (sistema is rag and q in respostas) else sistema.ask(q)  # reaproveita respostas da seção 1
        linhas.append({"pergunta": q[:70], "alvo": alvo, "pipeline": nome, "status": r.status,
                       **metricas(r.evidences, alvo), "%citadas": round(len(r.cited_refs) / max(len(r.evidences), 1) * 100),
                       "citacoes_invalidas": len(r.invalid_refs)})
aval = pd.DataFrame(linhas)
aval

Taxas na base: nota 1-2 = 26% | nota 4-5 = 66% | atrasado ou não entregue = 14%

,pergunta,alvo,pipeline,status,evidencias,sim_media,%nota_1_2,%nota_4_5,%atraso_ou_nao_entregue,%citadas,citacoes_invalidas
0,Quais são os principais problemas relatados pe...,neg,com multi-query,respondida,15.0,0.925,93.0,0.0,47.0,100,0
1,Quais são os principais problemas relatados pe...,neg,sem multi-query,sem_evidencias,NaN,NaN,NaN,NaN,NaN,0,0
2,Quais padrões podem ser identificados nas aval...,neg,com multi-query,respondida,15.0,0.936,100.0,0.0,27.0,100,0
3,Quais padrões podem ser identificados nas aval...,neg,sem multi-query,sem_evidencias,NaN,NaN,NaN,NaN,NaN,0,0
4,Existem padrões recorrentes nas avaliações rel...,NaN,com multi-query,respondida,15.0,0.928,27.0,67.0,13.0,67,0
5,Existem padrões recorrentes nas avaliações rel...,NaN,sem multi-query,sem_evidencias,NaN,NaN,NaN,NaN,NaN,0,0
6,Quais aspectos da experiência de compra são ma...,pos,com multi-query,respondida,15.0,0.937,0.0,100.0,7.0,93,0
7,Quais aspectos da experiência de compra são ma...,pos,sem multi-query,sem_evidencias,NaN,NaN,NaN,NaN,NaN,0,0
8,O que os clientes mais elogiam sobre a entrega?,pos,com multi-query,respondida,15.0,0.941,0.0,100.0,0.0,100,0
9,O que os clientes mais elogiam sobre a entrega?,pos,sem multi-query,respondida,5.0,0.894,0.0,100.0,0.0,100,0
10,O que os clientes relatam sobre problemas rela...,entrega,com multi-query,respondida,15.0,0.931,40.0,40.0,60.0,67,0
11,O que os clientes relatam sobre problemas rela...,entrega,sem multi-query,sem_evidencias,NaN,NaN,NaN,NaN,NaN,0,0
12,Quais avaliações sustentam a conclusão de que ...,entrega,com multi-query,respondida,15.0,0.921,60.0,33.0,47.0,93,0
13,Quais avaliações sustentam a conclusão de que ...,entrega,sem multi-query,respondida,15.0,0.896,47.0,40.0,40.0,60,0
14,Quais reclamações relacionadas à entrega apare...,entrega,com multi-query,respondida,15.0,0.928,60.0,27.0,67.0,80,0
15,Quais reclamações relacionadas à entrega apare...,entrega,sem multi-query,sem_evidencias,NaN,NaN,NaN,NaN,NaN,0,0

In [14]:
def acerto(row):
    return {"neg": row["%nota_1_2"], "pos": row["%nota_4_5"], "entrega": row["%atraso_ou_nao_entregue"]}.get(row["alvo"])
aval["coerencia_%"] = aval.apply(acerto, axis=1)
resumo = aval.dropna(subset=["coerencia_%"]).pivot_table(index="alvo", columns="pipeline", values="coerencia_%", aggfunc="mean").round(1)
resumo["taxa_na_base_%"] = pd.Series({"neg": base_neg, "pos": base_pos, "entrega": base_entrega}).mul(100).round(1)
resumo

pipeline  com multi-query  sem multi-query  taxa_na_base_%
alvo
entrega              58.0             40.0            13.5
neg                  96.5              NaN            25.8
pos                 100.0            100.0            65.6

In [15]:
print("Médias gerais por pipeline:")
aval.groupby("pipeline")[["evidencias", "sim_media", "%citadas", "citacoes_invalidas"]].mean().round(2)

Médias gerais por pipeline:

                 evidencias  sim_media  %citadas  citacoes_invalidas
pipeline
com multi-query        15.0       0.93      87.5                 0.0
sem multi-query        10.0       0.90      20.0                 0.0

In [16]:
aval.groupby(["pipeline", "status"]).size().unstack(fill_value=0)

status           respondida  sem_evidencias
pipeline
com multi-query           8               0
sem multi-query           2               6

### Leitura dos resultados

* A coerência das evidências com o tema da pergunta fica **muito acima da taxa da base**, o que indica que a
  recuperação semântica encontra avaliações realmente relacionadas (lembrando que os metadados não foram usados na busca).
* As respostas citam uma parcela grande das evidências e não há citações inválidas — os insights são
  **rastreáveis** até o `review_id` da avaliação.
* Os testes da seção 2 mostram as três guardas em ação: o sistema prefere declarar a falta de evidências a gerar uma
  resposta sem suporte.

**Limitações conhecidas**
* “Frequência” é estimada a partir da vizinhança semântica (até 1.000 avaliações), não de uma contagem exaustiva.
* Avaliações muito curtas (“ok”, “bom”) carregam pouco contexto; elas são deduplicadas mas permanecem na base.
* O viés de quem escreve comentários (clientes insatisfeitos comentam mais) deve ser considerado na interpretação.